In [1]:
import sys
print(sys.executable)

/opt/miniconda3/bin/python3.13

In [2]:
import sys
print(sys.executable)

/Users/rishabhbhardwaj/f1-race-engine/.venv/bin/python

In [4]:
import fastf1

print(fastf1.__version__)

3.8.3

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Everything is working.")

Matplotlib is building the font cache; this may take a moment.

Everything is working.

In [6]:
session = fastf1.get_session(2025, "British", "R")
session.load()

req         WARNING 	DEFAULT CACHE ENABLED! (24.0 KB) /Users/rishabhbhardwaj/Library/Caches/fastf1
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 43)
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 30: Position data is incomplete!
_api        WARNING 	Driver 31: Position data is incomplete!
_api        WARNING 	Driver  2: Position data is incomplete!
_api        WARNING 	Driver  3: Position data is incomplete!
_api        WARNING 	Driver  7: Position data is incomplete!
_api        WARNING 	Driver  8: Position data is incomplete!
_api        WARNING 	Driver  9: Position data is incomplete!
_api        WARNING 	Driver 11: Position data is incomplete!
_api        WARNING 	Driver 15: Position data is incomplete!
_api        WARNING 	Driver 17: Position data is incomplete!
_api        WARNING 	Driver 19: Position data is incomplete!
_api        WARNING 	Driver 20: Position data is incomplete!
_api        WARNING 	Driver 21: Position data is incomplete!
_api        WARNING 	Driver 24: Position data is incomplete!
_api        WARNING 	Driver 25: Position data is incomplete!
_api        WARNING 	Driver 26: Position data is incomplete!
_api        WARNING 	Driver 28: Position data is incomplete!
_api        WARNING 	Driver 29: Position data is incomplete!
_api        WARNING 	Driver 43: Position data is incomplete!
_api        WARNING 	Driver 44: Position data is incomplete!
_api        WARNING 	Driver 55: Position data is incomplete!
_api        WARNING 	Driver 63: Position data is incomplete!
_api        WARNING 	Driver 81: Position data is incomplete!
_api        WARNING 	Driver 87: Position data is incomplete!
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '27', '44', '1', '10', '18', '23', '14', '63', '87', '55', '31', '16', '22', '12', '6', '5', '30', '43']

In [7]:
session

2025 Season Round 12: British Grand Prix - Race

In [8]:
session.laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:55.042000,VER,1,0 days 00:01:45.820000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:41.707000,...,True,Red Bull Racing,0 days 00:56:09.003000,2025-07-06 14:03:49.616,12,1.0,False,,False,False
1,0 days 01:00:10.640000,VER,1,0 days 00:02:15.598000,2.0,1.0,NaT,NaT,0 days 00:00:45.755000,0 days 00:00:53.700000,...,True,Red Bull Racing,0 days 00:57:55.042000,2025-07-06 14:05:35.655,26,1.0,False,,False,False
2,0 days 01:02:27.997000,VER,1,0 days 00:02:17.357000,3.0,1.0,NaT,NaT,0 days 00:00:48.885000,0 days 00:00:50.924000,...,True,Red Bull Racing,0 days 01:00:10.640000,2025-07-06 14:07:51.253,6,1.0,False,,False,False
3,0 days 01:04:13.565000,VER,1,0 days 00:01:45.568000,4.0,1.0,NaT,NaT,0 days 00:00:36.223000,0 days 00:00:40.712000,...,True,Red Bull Racing,0 days 01:02:27.997000,2025-07-06 14:10:08.610,6712,1.0,False,,False,False
4,0 days 01:05:58.374000,VER,1,0 days 00:01:44.809000,5.0,1.0,NaT,NaT,0 days 00:00:31.996000,0 days 00:00:43.110000,...,True,Red Bull Racing,0 days 01:04:13.565000,2025-07-06 14:11:54.178,126,1.0,False,,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,0 days 02:28:31.132000,BEA,87,0 days 00:01:31.041000,48.0,3.0,NaT,NaT,0 days 00:00:29.191000,0 days 00:00:37.115000,...,True,Haas F1 Team,0 days 02:27:00.091000,2025-07-06 15:34:40.704,1,11.0,False,,False,True
821,0 days 02:30:02.405000,BEA,87,0 days 00:01:31.273000,49.0,3.0,NaT,NaT,0 days 00:00:29.030000,0 days 00:00:37.237000,...,True,Haas F1 Team,0 days 02:28:31.132000,2025-07-06 15:36:11.745,1,11.0,False,,False,True
822,0 days 02:31:33.326000,BEA,87,0 days 00:01:30.921000,50.0,3.0,NaT,NaT,0 days 00:00:29.104000,0 days 00:00:37.062000,...,True,Haas F1 Team,0 days 02:30:02.405000,2025-07-06 15:37:43.018,1,11.0,False,,False,True
823,0 days 02:33:04.447000,BEA,87,0 days 00:01:31.121000,51.0,3.0,NaT,NaT,0 days 00:00:29.159000,0 days 00:00:36.990000,...,True,Haas F1 Team,0 days 02:31:33.326000,2025-07-06 15:39:13.939,1,11.0,False,,False,True
824,0 days 02:34:37.032000,BEA,87,0 days 00:01:32.585000,52.0,3.0,NaT,NaT,0 days 00:00:29.012000,0 days 00:00:38.590000,...,True,Haas F1 Team,0 days 02:33:04.447000,2025-07-06 15:40:45.060,1,11.0,False,,False,True

In [9]:
session.laps.columns.tolist()

['Time',
 'Driver',
 'DriverNumber',
 'LapTime',
 'LapNumber',
 'Stint',
 'PitOutTime',
 'PitInTime',
 'Sector1Time',
 'Sector2Time',
 'Sector3Time',
 'Sector1SessionTime',
 'Sector2SessionTime',
 'Sector3SessionTime',
 'SpeedI1',
 'SpeedI2',
 'SpeedFL',
 'SpeedST',
 'IsPersonalBest',
 'Compound',
 'TyreLife',
 'FreshTyre',
 'Team',
 'LapStartTime',
 'LapStartDate',
 'TrackStatus',
 'Position',
 'Deleted',
 'DeletedReason',
 'FastF1Generated',
 'IsAccurate']

In [10]:
session.race_control_messages

,Time,Category,Message,Status,Flag,Scope,Sector,RacingNumber,Lap
0,2025-07-06 13:19:04,Other,AWNINGS MAY BE USED,None,None,None,NaN,None,1
1,2025-07-06 13:20:01,Flag,GREEN LIGHT - PIT EXIT OPEN,None,GREEN,Track,NaN,None,1
2,2025-07-06 13:30:01,Other,PIT EXIT CLOSED,None,None,None,NaN,None,1
3,2025-07-06 13:31:23,Flag,YELLOW IN TRACK SECTOR 13,None,YELLOW,Sector,13.0,None,1
4,2025-07-06 13:31:24,Other,DRS DISABLED IN ZONE 2,None,None,None,NaN,None,1
...,...,...,...,...,...,...,...,...,...
153,2025-07-06 15:34:12,Other,FIA STEWARDS: TURN 15 INCIDENT INVOLVING CARS ...,None,None,None,NaN,None,48
154,2025-07-06 15:37:55,Other,CAR 55 (SAI) TIME 1:34.080 DELETED - TRACK LIM...,None,None,None,NaN,None,50
155,2025-07-06 15:41:05,Flag,CHEQUERED FLAG,None,CHEQUERED,Track,NaN,None,52
156,2025-07-06 15:43:42,Other,ALL PASS HOLDERS MAY ACCESS THE PIT LANE,None,None,None,NaN,None,52
157,2025-07-06 15:44:55,Other,CAR 81 (PIA) TIME 1:32.340 DELETED - TRACK LIM...,None,None,None,NaN,None,52

In [11]:
session.race_control_messages[
    ["Time", "Category", "Message"]
]

,Time,Category,Message
0,2025-07-06 13:19:04,Other,AWNINGS MAY BE USED
1,2025-07-06 13:20:01,Flag,GREEN LIGHT - PIT EXIT OPEN
2,2025-07-06 13:30:01,Other,PIT EXIT CLOSED
3,2025-07-06 13:31:23,Flag,YELLOW IN TRACK SECTOR 13
4,2025-07-06 13:31:24,Other,DRS DISABLED IN ZONE 2
...,...,...,...
153,2025-07-06 15:34:12,Other,FIA STEWARDS: TURN 15 INCIDENT INVOLVING CARS ...
154,2025-07-06 15:37:55,Other,CAR 55 (SAI) TIME 1:34.080 DELETED - TRACK LIM...
155,2025-07-06 15:41:05,Flag,CHEQUERED FLAG
156,2025-07-06 15:43:42,Other,ALL PASS HOLDERS MAY ACCESS THE PIT LANE
157,2025-07-06 15:44:55,Other,CAR 81 (PIA) TIME 1:32.340 DELETED - TRACK LIM...

In [12]:
session.track_status

                     Time Status      Message
0         0 days 00:00:00      2       Yellow
1  0 days 00:06:30.062000      1     AllClear
2  0 days 00:23:42.510000      2       Yellow
3  0 days 00:43:10.428000      1     AllClear
4  0 days 00:56:42.108000      2       Yellow
5  0 days 00:56:58.107000      1     AllClear
6  0 days 00:57:02.700000      2       Yellow
7  0 days 00:58:07.014000      6  VSCDeployed
8  0 days 01:02:37.206000      7    VSCEnding
9  0 days 01:02:50.160000      1     AllClear
10 0 days 01:03:22.008000      2       Yellow
11 0 days 01:03:41.088000      1     AllClear
12 0 days 01:04:55.334000      2       Yellow
13 0 days 01:05:58.175000      6  VSCDeployed
14 0 days 01:09:22.963000      7    VSCEnding
15 0 days 01:09:36.809000      1     AllClear
16 0 days 01:21:18.098000      2       Yellow
17 0 days 01:21:20.598000      1     AllClear
18 0 days 01:21:33.748000      4   SCDeployed
19 0 days 01:31:31.469000      1     AllClear
20 0 days 01:33:20.525000      2       Yellow
21 0 days 01:33:34.741000      4   SCDeployed
22 0 days 01:41:47.464000      1     AllClear
23 0 days 01:42:57.697000      2       Yellow
24 0 days 01:43:00.324000      1     AllClear
25 0 days 02:13:15.635000      2       Yellow
26 0 days 02:13:25.454000      1     AllClear
27 0 days 02:18:27.504000      2       Yellow
28 0 days 02:18:29.505000      1     AllClear
29 0 days 02:19:40.697000      2       Yellow
30 0 days 02:19:50.537000      1     AllClear
31 0 days 02:20:30.581000      2       Yellow
32 0 days 02:20:41.958000      1     AllClear

In [13]:
session.weather_data.head()

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:19.723000,18.0,85.0,988.6,False,24.2,174,0.7
1,0 days 00:01:19.675000,18.0,83.0,988.5,False,24.6,111,0.9
2,0 days 00:02:19.683000,18.1,82.0,988.6,False,24.6,61,2.2
3,0 days 00:03:19.685000,18.0,81.0,988.6,False,24.1,71,3.1
4,0 days 00:04:19.683000,18.0,79.0,988.5,False,23.9,28,3.0

In [14]:
missing = session.laps.isna().mean().sort_values(ascending=False)

missing

PitInTime             0.956364
PitOutTime            0.951515
LapTime               0.110303
SpeedFL               0.047273
Sector1SessionTime    0.027879
Sector1Time           0.025455
Sector2SessionTime    0.003636
SpeedST               0.003636
Position              0.003636
SpeedI1               0.003636
Sector3SessionTime    0.003636
SpeedI2               0.003636
Sector3Time           0.003636
Sector2Time           0.003636
DeletedReason         0.002424
IsPersonalBest        0.002424
Team                  0.000000
Deleted               0.000000
FastF1Generated       0.000000
TrackStatus           0.000000
LapStartDate          0.000000
LapStartTime          0.000000
Time                  0.000000
FreshTyre             0.000000
TyreLife              0.000000
Compound              0.000000
Driver                0.000000
Stint                 0.000000
LapNumber             0.000000
DriverNumber          0.000000
IsAccurate            0.000000
dtype: float64

In [15]:
session.laps["Driver"].value_counts()

Driver
VER    52
GAS    52
PIA    52
RUS    52
SAI    52
HAM    52
NOR    52
OCO    52
BEA    52
HUL    52
ALB    52
STR    52
LEC    52
ALO    52
TSU    51
ANT    23
HAD    18
BOR     4
LAW     1
Name: count, dtype: int64

In [16]:
session.laps["TrackStatus"].value_counts()

TrackStatus
1       485
12       83
4        80
41       33
124      32
6        30
126      22
671      22
26       13
6712      8
21        5
67        5
712       5
14        2
Name: count, dtype: int64

In [22]:
session.laps[["LapNumber", "Driver", "TrackStatus"]].head(10)

   LapNumber Driver TrackStatus
0        1.0    VER          12
1        2.0    VER          26
2        3.0    VER           6
3        4.0    VER        6712
4        5.0    VER         126
5        6.0    VER           6
6        7.0    VER         671
7        8.0    VER           1
8        9.0    VER           1
9       10.0    VER           1

In [28]:
session.laps[
    session.laps["TrackStatus"] != "1"
][["LapNumber", "Driver", "TrackStatus"]].head(50)

     LapNumber Driver TrackStatus
0          1.0    VER          12
1          2.0    VER          26
2          3.0    VER           6
3          4.0    VER        6712
4          5.0    VER         126
5          6.0    VER           6
6          7.0    VER         671
12        13.0    VER          12
13        14.0    VER          14
14        15.0    VER           4
15        16.0    VER           4
16        17.0    VER          41
17        18.0    VER         124
18        19.0    VER           4
19        20.0    VER           4
20        21.0    VER          41
21        22.0    VER          12
38        39.0    VER          12
41        42.0    VER          12
42        43.0    VER          12
43        44.0    VER          21
52         1.0    GAS          12
53         2.0    GAS          26
54         3.0    GAS           6
55         4.0    GAS        6712
56         5.0    GAS         126
57         6.0    GAS           6
58         7.0    GAS         671
64        13.0    GAS         124
65        14.0    GAS           4
66        15.0    GAS           4
67        16.0    GAS           4
68        17.0    GAS          41
69        18.0    GAS         124
70        19.0    GAS           4
71        20.0    GAS           4
72        21.0    GAS          41
73        22.0    GAS          12
90        39.0    GAS          12
91        40.0    GAS          21
93        42.0    GAS          12
94        43.0    GAS          12
95        44.0    GAS          21
104        1.0    ANT          12
105        2.0    ANT          26
106        3.0    ANT          67
107        4.0    ANT         712
108        5.0    ANT         126
109        6.0    ANT           6
110        7.0    ANT         671

In [30]:
session.track_status

                     Time Status      Message
0         0 days 00:00:00      2       Yellow
1  0 days 00:06:30.062000      1     AllClear
2  0 days 00:23:42.510000      2       Yellow
3  0 days 00:43:10.428000      1     AllClear
4  0 days 00:56:42.108000      2       Yellow
5  0 days 00:56:58.107000      1     AllClear
6  0 days 00:57:02.700000      2       Yellow
7  0 days 00:58:07.014000      6  VSCDeployed
8  0 days 01:02:37.206000      7    VSCEnding
9  0 days 01:02:50.160000      1     AllClear
10 0 days 01:03:22.008000      2       Yellow
11 0 days 01:03:41.088000      1     AllClear
12 0 days 01:04:55.334000      2       Yellow
13 0 days 01:05:58.175000      6  VSCDeployed
14 0 days 01:09:22.963000      7    VSCEnding
15 0 days 01:09:36.809000      1     AllClear
16 0 days 01:21:18.098000      2       Yellow
17 0 days 01:21:20.598000      1     AllClear
18 0 days 01:21:33.748000      4   SCDeployed
19 0 days 01:31:31.469000      1     AllClear
20 0 days 01:33:20.525000      2       Yellow
21 0 days 01:33:34.741000      4   SCDeployed
22 0 days 01:41:47.464000      1     AllClear
23 0 days 01:42:57.697000      2       Yellow
24 0 days 01:43:00.324000      1     AllClear
25 0 days 02:13:15.635000      2       Yellow
26 0 days 02:13:25.454000      1     AllClear
27 0 days 02:18:27.504000      2       Yellow
28 0 days 02:18:29.505000      1     AllClear
29 0 days 02:19:40.697000      2       Yellow
30 0 days 02:19:50.537000      1     AllClear
31 0 days 02:20:30.581000      2       Yellow
32 0 days 02:20:41.958000      1     AllClear

In [31]:
session.track_status

                     Time Status      Message
0         0 days 00:00:00      2       Yellow
1  0 days 00:06:30.062000      1     AllClear
2  0 days 00:23:42.510000      2       Yellow
3  0 days 00:43:10.428000      1     AllClear
4  0 days 00:56:42.108000      2       Yellow
5  0 days 00:56:58.107000      1     AllClear
6  0 days 00:57:02.700000      2       Yellow
7  0 days 00:58:07.014000      6  VSCDeployed
8  0 days 01:02:37.206000      7    VSCEnding
9  0 days 01:02:50.160000      1     AllClear
10 0 days 01:03:22.008000      2       Yellow
11 0 days 01:03:41.088000      1     AllClear
12 0 days 01:04:55.334000      2       Yellow
13 0 days 01:05:58.175000      6  VSCDeployed
14 0 days 01:09:22.963000      7    VSCEnding
15 0 days 01:09:36.809000      1     AllClear
16 0 days 01:21:18.098000      2       Yellow
17 0 days 01:21:20.598000      1     AllClear
18 0 days 01:21:33.748000      4   SCDeployed
19 0 days 01:31:31.469000      1     AllClear
20 0 days 01:33:20.525000      2       Yellow
21 0 days 01:33:34.741000      4   SCDeployed
22 0 days 01:41:47.464000      1     AllClear
23 0 days 01:42:57.697000      2       Yellow
24 0 days 01:43:00.324000      1     AllClear
25 0 days 02:13:15.635000      2       Yellow
26 0 days 02:13:25.454000      1     AllClear
27 0 days 02:18:27.504000      2       Yellow
28 0 days 02:18:29.505000      1     AllClear
29 0 days 02:19:40.697000      2       Yellow
30 0 days 02:19:50.537000      1     AllClear
31 0 days 02:20:30.581000      2       Yellow
32 0 days 02:20:41.958000      1     AllClear

In [32]:
session.race_control_messages.columns

Index(['Time', 'Category', 'Message', 'Status', 'Flag', 'Scope', 'Sector',
       'RacingNumber', 'Lap'],
      dtype='object')

In [34]:
session.race_control_messages.head(20)

,Time,Category,Message,Status,Flag,Scope,Sector,RacingNumber,Lap
0,2025-07-06 13:19:04,Other,AWNINGS MAY BE USED,None,None,None,NaN,None,1
1,2025-07-06 13:20:01,Flag,GREEN LIGHT - PIT EXIT OPEN,None,GREEN,Track,NaN,None,1
2,2025-07-06 13:30:01,Other,PIT EXIT CLOSED,None,None,None,NaN,None,1
3,2025-07-06 13:31:23,Flag,YELLOW IN TRACK SECTOR 13,None,YELLOW,Sector,13.0,None,1
4,2025-07-06 13:31:24,Other,DRS DISABLED IN ZONE 2,None,None,None,NaN,None,1
5,2025-07-06 13:31:29,Flag,YELLOW IN TRACK SECTOR 7,None,YELLOW,Sector,7.0,None,1
6,2025-07-06 13:31:30,Flag,YELLOW IN TRACK SECTOR 12,None,YELLOW,Sector,12.0,None,1
7,2025-07-06 13:31:30,Other,DRS DISABLED IN ZONE 1,None,None,None,NaN,None,1
8,2025-07-06 13:31:43,Flag,DOUBLE YELLOW IN TRACK SECTOR 8,None,DOUBLE YELLOW,Sector,8.0,None,1
9,2025-07-06 13:32:01,Flag,YELLOW IN TRACK SECTOR 16,None,YELLOW,Sector,16.0,None,1
10,2025-07-06 13:32:07,Flag,YELLOW IN TRACK SECTOR 6,None,YELLOW,Sector,6.0,None,1
11,2025-07-06 13:32:19,Flag,DOUBLE YELLOW IN TRACK SECTOR 9,None,DOUBLE YELLOW,Sector,9.0,None,1
12,2025-07-06 13:32:27,Flag,DOUBLE YELLOW IN TRACK SECTOR 10,None,DOUBLE YELLOW,Sector,10.0,None,1
13,2025-07-06 13:32:27,Flag,YELLOW IN TRACK SECTOR 11,None,YELLOW,Sector,11.0,None,1
14,2025-07-06 13:32:36,Flag,YELLOW IN TRACK SECTOR 4,None,YELLOW,Sector,4.0,None,1
15,2025-07-06 13:32:37,Flag,DOUBLE YELLOW IN TRACK SECTOR 11,None,DOUBLE YELLOW,Sector,11.0,None,1
16,2025-07-06 13:32:52,Flag,DOUBLE YELLOW IN TRACK SECTOR 6,None,DOUBLE YELLOW,Sector,6.0,None,1
17,2025-07-06 13:33:05,Flag,DOUBLE YELLOW IN TRACK SECTOR 7,None,DOUBLE YELLOW,Sector,7.0,None,1
18,2025-07-06 13:33:58,Flag,YELLOW IN TRACK SECTOR 6,None,YELLOW,Sector,6.0,None,1
19,2025-07-06 13:34:00,Flag,CLEAR IN TRACK SECTOR 4,None,CLEAR,Sector,4.0,None,1

In [35]:
session.race_control_messages[
    session.race_control_messages["Message"].str.contains(
        "SAFETY CAR|VSC",
        case=False,
        na=False
    )
][[
    "Time",
    "Message",
    "Flag",
    "Scope",
    "Lap"
]]

,Time,Message,Flag,Scope,Lap
57,2025-07-06 13:55:00,FORMATION LAP WILL BE STARTED BEHIND THE SAFET...,None,None,1
67,2025-07-06 14:05:48,VIRTUAL SAFETY CAR DEPLOYED,None,None,2
72,2025-07-06 14:10:18,VIRTUAL SAFETY CAR ENDING,None,None,4
81,2025-07-06 14:13:39,VIRTUAL SAFETY CAR DEPLOYED,None,None,5
87,2025-07-06 14:17:04,VIRTUAL SAFETY CAR ENDING,None,None,7
97,2025-07-06 14:29:14,SAFETY CAR DEPLOYED,None,None,14
99,2025-07-06 14:38:36,SAFETY CAR IN THIS LAP,None,None,17
102,2025-07-06 14:41:15,SAFETY CAR DEPLOYED,None,None,18
108,2025-07-06 14:49:02,SAFETY CAR IN THIS LAP,None,None,21
110,2025-07-06 14:49:47,INCIDENT INVOLVING CAR 81 (PIA) NOTED - SAFETY...,None,None,22
114,2025-07-06 14:51:57,FIA STEWARDS: INCIDENT INVOLVING CAR 81 (PIA) ...,None,None,23
115,2025-07-06 14:55:02,FIA STEWARDS: 10 SECOND TIME PENALTY FOR CAR 8...,None,None,25
152,2025-07-06 15:33:41,FIA STEWARDS: PENALTY SERVED - 10 SECOND TIME ...,None,None,48

In [36]:
session.race_control_messages[
    session.race_control_messages["Scope"] == "Track"
][[
    "Time",
    "Message",
    "Flag",
    "Lap"
]]

                   Time                      Message       Flag  Lap
1   2025-07-06 13:20:01  GREEN LIGHT - PIT EXIT OPEN      GREEN    1
61  2025-07-06 14:03:50  GREEN LIGHT - PIT EXIT OPEN      GREEN    1
75  2025-07-06 14:10:31                  TRACK CLEAR      CLEAR    4
88  2025-07-06 14:17:17                  TRACK CLEAR      CLEAR    7
100 2025-07-06 14:39:12                  TRACK CLEAR      CLEAR   17
109 2025-07-06 14:49:28                  TRACK CLEAR      CLEAR   21
155 2025-07-06 15:41:05               CHEQUERED FLAG  CHEQUERED   52

In [37]:
events = session.race_control_messages.copy()

events = events[
    events["Message"].str.contains(
        "VIRTUAL SAFETY CAR|SAFETY CAR",
        case=False,
        na=False
    )
][[
    "Time",
    "Message",
    "Lap"
]].copy()

events

,Time,Message,Lap
57,2025-07-06 13:55:00,FORMATION LAP WILL BE STARTED BEHIND THE SAFET...,1
67,2025-07-06 14:05:48,VIRTUAL SAFETY CAR DEPLOYED,2
72,2025-07-06 14:10:18,VIRTUAL SAFETY CAR ENDING,4
81,2025-07-06 14:13:39,VIRTUAL SAFETY CAR DEPLOYED,5
87,2025-07-06 14:17:04,VIRTUAL SAFETY CAR ENDING,7
97,2025-07-06 14:29:14,SAFETY CAR DEPLOYED,14
99,2025-07-06 14:38:36,SAFETY CAR IN THIS LAP,17
102,2025-07-06 14:41:15,SAFETY CAR DEPLOYED,18
108,2025-07-06 14:49:02,SAFETY CAR IN THIS LAP,21
110,2025-07-06 14:49:47,INCIDENT INVOLVING CAR 81 (PIA) NOTED - SAFETY...,22
114,2025-07-06 14:51:57,FIA STEWARDS: INCIDENT INVOLVING CAR 81 (PIA) ...,23
115,2025-07-06 14:55:02,FIA STEWARDS: 10 SECOND TIME PENALTY FOR CAR 8...,25
152,2025-07-06 15:33:41,FIA STEWARDS: PENALTY SERVED - 10 SECOND TIME ...,48

In [38]:
def classify_event(message):
    message = message.upper()

    if "VIRTUAL SAFETY CAR DEPLOYED" in message:
        return "VSC_START"
    
    if "VIRTUAL SAFETY CAR ENDING" in message:
        return "VSC_END"
    
    if "SAFETY CAR DEPLOYED" in message:
        return "SC_START"
    
    if "SAFETY CAR IN THIS LAP" in message:
        return "SC_END"
    
    return "OTHER"

In [39]:
events["EventType"] = events["Message"].apply(classify_event)

events

,Time,Message,Lap,EventType
57,2025-07-06 13:55:00,FORMATION LAP WILL BE STARTED BEHIND THE SAFET...,1,OTHER
67,2025-07-06 14:05:48,VIRTUAL SAFETY CAR DEPLOYED,2,VSC_START
72,2025-07-06 14:10:18,VIRTUAL SAFETY CAR ENDING,4,VSC_END
81,2025-07-06 14:13:39,VIRTUAL SAFETY CAR DEPLOYED,5,VSC_START
87,2025-07-06 14:17:04,VIRTUAL SAFETY CAR ENDING,7,VSC_END
97,2025-07-06 14:29:14,SAFETY CAR DEPLOYED,14,SC_START
99,2025-07-06 14:38:36,SAFETY CAR IN THIS LAP,17,SC_END
102,2025-07-06 14:41:15,SAFETY CAR DEPLOYED,18,SC_START
108,2025-07-06 14:49:02,SAFETY CAR IN THIS LAP,21,SC_END
110,2025-07-06 14:49:47,INCIDENT INVOLVING CAR 81 (PIA) NOTED - SAFETY...,22,OTHER
114,2025-07-06 14:51:57,FIA STEWARDS: INCIDENT INVOLVING CAR 81 (PIA) ...,23,OTHER
115,2025-07-06 14:55:02,FIA STEWARDS: 10 SECOND TIME PENALTY FOR CAR 8...,25,OTHER
152,2025-07-06 15:33:41,FIA STEWARDS: PENALTY SERVED - 10 SECOND TIME ...,48,OTHER

In [40]:
events = events[events["EventType"] != "OTHER"].copy()

In [41]:
events[["Time", "Lap", "EventType"]].reset_index(drop=True)

                 Time  Lap  EventType
0 2025-07-06 14:05:48    2  VSC_START
1 2025-07-06 14:10:18    4    VSC_END
2 2025-07-06 14:13:39    5  VSC_START
3 2025-07-06 14:17:04    7    VSC_END
4 2025-07-06 14:29:14   14   SC_START
5 2025-07-06 14:38:36   17     SC_END
6 2025-07-06 14:41:15   18   SC_START
7 2025-07-06 14:49:02   21     SC_END

In [44]:
session.laps[
    session.laps["Driver"] == "VER"
][[
    "Time",
    "LapNumber",
    "LapTime",
    "TrackStatus"
]].head(52)

                     Time  LapNumber                LapTime TrackStatus
0  0 days 00:57:55.042000        1.0 0 days 00:01:45.820000          12
1  0 days 01:00:10.640000        2.0 0 days 00:02:15.598000          26
2  0 days 01:02:27.997000        3.0 0 days 00:02:17.357000           6
3  0 days 01:04:13.565000        4.0 0 days 00:01:45.568000        6712
4  0 days 01:05:58.374000        5.0 0 days 00:01:44.809000         126
5  0 days 01:08:18.163000        6.0 0 days 00:02:19.789000           6
6  0 days 01:10:20.710000        7.0 0 days 00:02:02.547000         671
7  0 days 01:12:06.544000        8.0 0 days 00:01:45.834000           1
8  0 days 01:13:52.870000        9.0 0 days 00:01:46.326000           1
9  0 days 01:15:39.302000       10.0 0 days 00:01:46.432000           1
10 0 days 01:17:29.799000       11.0 0 days 00:01:50.497000           1
11 0 days 01:19:36.713000       12.0 0 days 00:02:06.914000           1
12 0 days 01:21:27.937000       13.0 0 days 00:01:51.224000          12
13 0 days 01:23:44.757000       14.0 0 days 00:02:16.820000          14
14 0 days 01:26:22.453000       15.0                    NaT           4
15 0 days 01:29:07.068000       16.0                    NaT           4
16 0 days 01:32:03.893000       17.0                    NaT          41
17 0 days 01:34:02.558000       18.0 0 days 00:01:58.665000         124
18 0 days 01:36:42.205000       19.0                    NaT           4
19 0 days 01:39:24.716000       20.0                    NaT           4
20 0 days 01:42:12.941000       21.0                    NaT          41
21 0 days 01:44:03.959000       22.0 0 days 00:01:51.018000          12
22 0 days 01:45:49.822000       23.0 0 days 00:01:45.863000           1
23 0 days 01:47:34.839000       24.0 0 days 00:01:45.017000           1
24 0 days 01:49:18.978000       25.0 0 days 00:01:44.139000           1
25 0 days 01:51:03.282000       26.0 0 days 00:01:44.304000           1
26 0 days 01:52:47.185000       27.0 0 days 00:01:43.903000           1
27 0 days 01:54:31.428000       28.0 0 days 00:01:44.243000           1
28 0 days 01:56:16.144000       29.0 0 days 00:01:44.716000           1
29 0 days 01:58:00.865000       30.0 0 days 00:01:44.721000           1
30 0 days 01:59:45.424000       31.0 0 days 00:01:44.559000           1
31 0 days 02:01:29.935000       32.0 0 days 00:01:44.511000           1
32 0 days 02:03:14.241000       33.0 0 days 00:01:44.306000           1
33 0 days 02:04:58.164000       34.0 0 days 00:01:43.923000           1
34 0 days 02:06:40.781000       35.0 0 days 00:01:42.617000           1
35 0 days 02:08:22.705000       36.0 0 days 00:01:41.924000           1
36 0 days 02:10:04.288000       37.0 0 days 00:01:41.583000           1
37 0 days 02:11:45.478000       38.0 0 days 00:01:41.190000           1
38 0 days 02:13:26.236000       39.0 0 days 00:01:40.758000          12
39 0 days 02:15:07.710000       40.0 0 days 00:01:41.474000           1
40 0 days 02:16:47.175000       41.0 0 days 00:01:39.465000           1
41 0 days 02:18:54.959000       42.0 0 days 00:02:07.784000          12
42 0 days 02:20:34.438000       43.0 0 days 00:01:39.479000          12
43 0 days 02:22:09.603000       44.0 0 days 00:01:35.165000          21
44 0 days 02:23:43.447000       45.0 0 days 00:01:33.844000           1
45 0 days 02:25:16.407000       46.0 0 days 00:01:32.960000           1
46 0 days 02:26:48.119000       47.0 0 days 00:01:31.712000           1
47 0 days 02:28:18.895000       48.0 0 days 00:01:30.776000           1
48 0 days 02:29:49.074000       49.0 0 days 00:01:30.179000           1
49 0 days 02:31:19.364000       50.0 0 days 00:01:30.290000           1
50 0 days 02:32:50.337000       51.0 0 days 00:01:30.973000           1
51 0 days 02:34:21.726000       52.0 0 days 00:01:31.389000           1